"""FortiGate-only Excel presentation schema.

This module defines workbook structure only.

It contains no parsing logic, FortiOS defaults, migration IR,
target-vendor concepts, or compatibility filtering.
"""

from __future__ import annotations


OBJECT_TAIL = (
    "Analysis Status",
    "Extraction Status",
    "Manual Review",
    "Review Reasons",
    "Source Explicit Fields",
    "Additional Settings",
)

CHILD_TAIL = (
    "Extraction Status",
    "Manual Review",
    "Review Reasons",
    "Additional Settings",
)

SOURCE_HEADERS = (
    "VDOM",
    "Source Path",
    "Object",
    "Parent / Subsection",
    "Setting",
    "Value",
    "Analysis Status",
    "Extraction Status",
    "Manual Review",
    "Review Reasons",
)


def object_headers(*fields: str) -> tuple[str, ...]:
    return (*fields, *OBJECT_TAIL)


def child_headers(*fields: str) -> tuple[str, ...]:
    return (*fields, *CHILD_TAIL)


SHEET_ORDER: tuple[str, ...] = (
    "Summary",
    "Review Required",

    # System
    "System Settings",
    "DNS Settings",
    "NTP Settings",

    # Network
    "Interfaces",
    "Interface Secondary IPs",
    "Zones",

    # Objects
    "Addresses",
    "Wildcard FQDN",
    "Address Groups",
    "Address Group Tags",
    "Service Categories",
    "Services",
    "Service Groups",
    "Schedules",
    "Schedule Groups",

    # Policies
    "Policies",
    "Local-In Policies",
    "Multicast Policies",
    "Policy Routes",

    # NAT
    "IP Pools",
    "Virtual IPs",
    "VIP Real Servers",
    "VIP Groups",
    "NAT Rules",

    # Routing
    "Routes",
    "Routing Protocol Settings",
    "Session TTL Settings",
    "Session TTL Overrides",

    # SD-WAN
    "SD-WAN",
    "SD-WAN Zones",
    "SD-WAN Members",
    "SD-WAN Health Checks",
    "SD-WAN Rules",
    "SD-WAN SLAs",
    "SD-WAN Duplication",
    "SD-WAN Neighbors",
    "SD-WAN Rule SLAs",

    # VPN
    "VPN Tunnels",
    "VPN Phase 2",

    # DHCP
    "DHCP Servers",
    "DHCP IP Ranges",
    "DHCP Exclude Ranges",
    "DHCP Reservations",

    # SSL VPN
    "SSL VPN Settings",
    "SSL VPN Portals",
    "SSL VPN Authentication Rules",
    "SSL VPN Host Checks",
    "SSL VPN Host Check Items",
    "SSL VPN Portal Split DNS",
    "SSL VPN Portal MAC Rules",
    "SSL VPN Portal OS Checks",
    "SSL VPN Bookmark Groups",
    "SSL VPN Bookmarks",
    "SSL VPN Bookmark Form Data",
    "SSL VPN Landing Pages",
    "SSL VPN Landing Form Data",

    # Identity
    "Local Users",
    "User Groups",
    "User Group Matches",
    "User Group Guests",
    "LDAP Servers",
    "RADIUS Servers",
    "RADIUS Accounting Servers",
    "TACACS+ Servers",
    "SAML Servers",
    "FSSO Servers",
    "FSSO AD Groups",
    "FSSO Polling",
    "FortiTokens",
    "Authentication Schemes",
    "Authentication Rules",
    "Authentication Sequences",
    "Identity Server Endpoints",

    # Administration
    "Administrators",
    "Admin Profiles",
    "Admin Profile Permissions",

    # Security
    "IPS Sensors",
    "IPS Sensor Entries",
    "IPS Exempt IPs",
    "Security Profiles",
    "Source Security Profile Setting",
    "SSL TLS Service Profiles",

    # Internet services
    "Internet Service Definitions",
    "Internet Service Def Entries",
    "Internet Service Def Ports",
    "Custom Internet Services",
    "Custom IS Entries",
    "Custom IS Ports",
    "Custom Internet Service Groups",
    "Internet Service Groups",
    "IS Additions",
    "IS Addition Entries",
    "IS Addition Ports",
    "IS Appends",
    "IS Extensions",
    "IS Extension Disabled",
    "IS Extension Entries",
    "IS Extension Ports",

    # Other FortiGate source
    "DoS Policies",
    "DoS Anomalies",
    "Firewall Sniffer",
    "IPv6 EH Filter",
    "External Resources",

    # Source appendix
    "FortiGate Source Configuration",
    "Firewall Policy Source Settings",
    "Interface Source Settings",
    "Interface Nested Configuration",

    # Validation / coverage
    "Unresolved References",
    "Warnings",
    "Unsupported",
    "Source Inventory",
    "Extraction Coverage",
)


SHEET_HEADERS: dict[str, tuple[str, ...]] = {
    "Summary": (),

    "Review Required": (
        "Severity",
        "Category",
        "Object",
        "Issue / Review Reason",
        "Status",
        "Source Sheet",
        "Source Row",
    ),

    "Interfaces": object_headers(
        "Name",
        "Relationship",
        "Topology Kind",
        "Alias",
        "Zone",
        "IP / Prefix",
        "Additional IPv4 Addresses",
        "Interface Type",
        "Role",
        "Addressing Mode",
        "DHCP Client",
        "PPPoE Mode",
        "PPPoE Username",
        "PPPoE Password Configured",
        "Management Access",
        "IPv6 Address",
        "IPv6 Management Access",
        "IPv6 Mode",
        "VLAN ID",
        "Parent / Underlay Interface",
        "Members",
        "Aggregate",
        "Physical Interfaces",
        "VRF",
        "MTU",
        "Link State",
        "Speed",
        "Duplex",
        "Media Type",
        "Description",
        "Source VDOM",
        "Topology Issues",
    ),

    "Interface Secondary IPs": child_headers(
        "Interface",
        "Secondary IP Status",
        "Source ID",
        "IP / Prefix",
        "Management Access",
    ),

    "Zones": object_headers(
        "VDOM",
        "Name",
        "Zone Type",
        "Members",
        "Configured Intrazone",
        "Description",
        "Source Path",
    ),

    "Addresses": object_headers(
        "Name",
        "Type",
        "Value",
        "Address Family",
        "Associated Interface",
        "Allow Routing",
        "Tags",
        "Description",
        "Source Section",
    ),

    "Wildcard FQDN": object_headers(
        "Name",
        "Wildcard FQDN",
        "Description",
        "Source VDOM",
    ),

    "Address Groups": object_headers(
        "Name",
        "Address Family",
        "Group Type",
        "Members",
        "Exclusion Enabled",
        "Exclude Members",
        "Allow Routing",
        "Tags",
        "Description",
    ),

    "Address Group Tags": child_headers(
        "Group Name",
        "Address Family",
        "Tag Entry",
        "Category",
        "Tags",
    ),

    "Service Categories": child_headers(
        "Name",
        "Description",
    ),

    "Services": object_headers(
        "Name",
        "Category",
        "Configured Protocol",
        "Effective Protocol",
        "Protocol / Destination Port",
        "Source Protocol Number",
        "Source Port Constraint",
        "Description",
    ),

    "Service Groups": object_headers(
        "Name",
        "Members",
        "Description",
    ),

    "Policies": object_headers(
        "Rule #",
        "Name",
        "Normalized Name",
        "Source Interface",
        "Source Addresses",
        "Source Address Negate",
        "Source IPv6 Address",
        "Source IPv6 Address Negate",
        "Destination Interface",
        "Destination Addresses",
        "Destination Address Negate",
        "Destination IPv6 Address",
        "Destination IPv6 Address Negate",
        "Services",
        "Service Negate",
        "Action",
        "Schedule",
        "Disabled",
        "NAT Enabled",
        "IP Pool Enabled",
        "NAT Pool",
        "NAT Pool IPv6",
        "VPN Tunnel",
        "Internet Service Status",
        "Internet Services",
        "User Groups",
        "Users",
        "UTM Status",
        "Security Profile Group",
        "Antivirus",
        "IPS Sensor",
        "Web Filter",
        "Application List",
        "SSL/SSH Profile",
        "Source Profile Type",
        "Source Profile Group",
        "Log Setting",
        "Comments",
        "Source Policy ID",
    ),

    "IP Pools": object_headers(
        "Name",
        "Type",
        "Start IP",
        "End IP",
        "Source Start IP",
        "Source End IP",
        "Start Port",
        "End Port",
        "Associated Interface",
        "ARP Reply",
        "ARP Interface",
        "Permit Any Host",
        "Excluded IPs",
        "NAT64",
        "Add NAT64 Route",
        "Description",
        "VDOM",
    ),

    "Virtual IPs": object_headers(
        "Name",
        "Type",
        "Status",
        "External IP",
        "External Address Objects",
        "External Interface",
        "Mapped IPs",
        "Mapped Address",
        "Port Forward",
        "Protocol",
        "External Port",
        "Mapped Port",
        "ARP Reply",
        "NAT Source VIP",
        "Services",
        "Load Balance Method",
        "Server Type",
        "Monitors",
        "Description",
        "Source UUID",
        "VDOM",
    ),

    "VIP Real Servers": child_headers(
        "VIP Name",
        "Server ID",
        "IP",
        "Address",
        "Port",
        "Status",
        "Weight",
        "Monitors",
        "VDOM",
    ),

    "VIP Groups": object_headers(
        "Name",
        "Interface",
        "Members",
        "Comments",
        "Source UUID",
        "VDOM",
    ),

    "NAT Rules": (
        "Rule #",
        "Name",
        "Type",
        "Enabled",
        "Source Interface",
        "Destination Interface",
        "Source Addresses",
        "Destination Addresses",
        "Services",
        "Source Translation Mode",
        "Translated Source",
        "IP Pool",
        "IP Pool Type",
        "Pool Excluded IPs",
        "Pool Source Start IP",
        "Pool Source End IP",
        "Egress Interfaces",
        "Description",
        "Source Policy ID",
        "Source Policy UUID",
        "VDOM",
        "Derived Issues",
        "Analysis Status",
        "Extraction Status",
        "Manual Review",
        "Review Reasons",
    ),

    "Routes": object_headers(
        "Route ID",
        "Destination",
        "Destination Address Object",
        "Interface",
        "Gateway",
        "Distance",
        "Priority",
        "Status",
        "SD-WAN Zone",
        "Preferred Source",
        "Source Prefix",
        "Dynamic Gateway",
        "Blackhole",
        "Description",
        "Address Family",
        "VDOM",
        "VRF",
    ),

    "SD-WAN": object_headers(
        "Status",
        "Load Balance Mode",
        "VDOM",
    ),

    "SD-WAN Zones": child_headers(
        "Zone Name",
        "VDOM",
    ),

    "SD-WAN Members": object_headers(
        "ID",
        "Interface",
        "Zone",
        "Gateway",
        "Source",
        "Cost",
        "Weight",
        "Priority",
        "Status",
        "Resolved Physical Interfaces",
        "Aggregate",
        "VDOM",
    ),

    "SD-WAN Health Checks": child_headers(
        "Name",
        "Server",
        "Members",
        "Protocol",
        "Interval",
        "Fail Time",
        "Recovery Time",
        "VDOM",
    ),

    "SD-WAN Rules": child_headers(
        "ID",
        "Name",
        "Status",
        "Mode",
        "Source",
        "Destination",
        "Priority Members",
        "Health Checks",
        "Priority Zones",
        "VDOM",
    ),

    "VPN Tunnels": object_headers(
        "Name",
        "Interface",
        "Remote Gateway IPv4",
        "Remote Gateway DDNS",
        "Type",
        "IKE Version",
        "Authentication Method",
        "Proposal",
        "DH Groups",
        "Key Lifetime",
        "NAT Traversal",
        "DPD",
        "Local Gateway",
        "Local ID",
        "Peer ID",
        "Certificates",
        "Comments",
        "VDOM",
        "Attached Interface",
        "Aggregate",
        "Resolved Physical Interfaces",
        "Topology Path",
        "Topology Issues",
    ),

    "VPN Phase 2": object_headers(
        "Name",
        "Phase 1",
        "Proposal",
        "PFS",
        "DH Groups",
        "Keylife Seconds",
        "Keylife KB",
        "Derived Source Range",
        "Derived Destination Range",
        "Source Address Type",
        "Source Subnet",
        "Source Range Start",
        "Source Range End",
        "Destination Address Type",
        "Destination Subnet",
        "Destination Range Start",
        "Destination Range End",
        "VDOM",
        "Comments",
    ),

    "DHCP Servers": object_headers(
        "Server ID",
        "Interface",
        "Status",
        "Server Type",
        "IP Mode",
        "Default Gateway",
        "Netmask",
        "Lease Time",
        "DNS Service",
        "DNS Server 1",
        "DNS Server 2",
        "DNS Server 3",
        "DNS Server 4",
        "Timezone Option",
        "Timezone",
        "Relay Agent",
        "VDOM",
    ),

    "DHCP IP Ranges": child_headers(
        "Server ID",
        "Interface",
        "Range ID",
        "Start IP",
        "End IP",
        "Lease Time",
        "VDOM",
        "Source Explicit Fields",
    ),

    "DHCP Exclude Ranges": child_headers(
        "Server ID",
        "Interface",
        "Range ID",
        "Start IP",
        "End IP",
        "Lease Time",
        "VDOM",
        "Source Explicit Fields",
    ),

    "DHCP Reservations": child_headers(
        "Server ID",
        "Interface",
        "Reservation ID",
        "IP Address",
        "MAC Address",
        "Description",
        "Action",
        "Type",
        "VDOM",
        "Source Explicit Fields",
    ),

    "SSL VPN Settings": object_headers(
        "Status",
        "Minimum Protocol",
        "Maximum Protocol",
        "Authentication Timeout",
        "Idle Timeout",
        "Port",
        "DNS Server 1",
        "DNS Server 2",
        "Server Certificate",
        "Source Interfaces",
        "Source Addresses",
        "Tunnel IP Pools",
        "Default Portal",
        "VDOM",
    ),

    "SSL VPN Portals": object_headers(
        "Name",
        "Tunnel Mode",
        "IPv6 Tunnel Mode",
        "IP Pools",
        "IPv6 Pools",
        "Split Tunneling",
        "Limit User Logins",
        "FortiClient Download",
        "Host Check",
        "Host Check Policies",
        "Split Tunneling Routing Addresses",
        "VDOM",
    ),

    "SSL VPN Authentication Rules": child_headers(
        "ID",
        "Auth",
        "Cipher",
        "Client Certificate",
        "Realm",
        "Source Interfaces",
        "Source Addresses",
        "Source Address Negate",
        "IPv6 Source Addresses",
        "IPv6 Source Address Negate",
        "Users",
        "User Peer",
        "Groups",
        "Portal",
    ),

    "SSL VPN Host Checks": object_headers(
        "Name",
        "Type",
        "OS Type",
        "Version",
        "GUID",
        "Check Item Count",
        "VDOM",
    ),

    "SSL VPN Host Check Items": child_headers(
        "Host Check",
        "ID",
        "Action",
        "Type",
        "Target",
        "MD5s",
        "Version",
    ),

    "Local Users": object_headers(
        "Name",
        "ID",
        "Status",
        "Type",
        "Password Configured",
        "Password Time",
        "Two Factor",
        "Two Factor Authentication",
        "Two Factor Notification",
        "FortiToken",
        "Email",
        "SMS Server",
        "SMS Custom Server",
        "SMS Phone",
        "LDAP Server",
        "RADIUS Server",
        "TACACS+ Server",
        "Auth Concurrent Override",
        "Auth Concurrent Value",
        "Auth Timeout",
        "Password Policy",
        "Workstation",
        "Username Sensitivity",
        "PPK Identity",
        "PPK Secret Configured",
        "VDOM",
    ),

    "User Groups": object_headers(
        "Name",
        "ID",
        "Group Type",
        "Members",
        "Match Count",
        "Auth Concurrent Override",
        "Auth Concurrent Value",
        "Auth Timeout",
        "VDOM",
    ),

    "User Group Matches": child_headers(
        "User Group",
        "Match ID",
        "Server Name",
        "Group Name",
        "VDOM",
    ),

    "User Group Guests": child_headers(
        "User Group",
        "Guest ID",
        "Name",
        "User ID",
        "Email",
        "Mobile Phone",
        "Expiration",
        "Sponsor",
        "Comment",
        "Password Configured",
        "VDOM",
    ),

    "Administrators": object_headers(
        "Name",
        "Access Profile",
        "VDOMs",
        "IPv4 Trusted Hosts",
        "IPv6 Trusted Hosts",
        "Two Factor",
        "Two Factor Authentication",
        "Two Factor Notification",
        "Remote Auth",
        "Remote Group",
        "Credential Configured",
        "FortiToken",
        "Guest User Groups",
        "Schedule",
        "Peer Auth",
        "Peer Group",
        "SSH Certificate",
    ),

    "Admin Profiles": object_headers(
        "Name",
    ),

    "Admin Profile Permissions": child_headers(
        "Profile",
        "Permission Group",
        "Setting",
        "Value",
    ),

    "IPS Sensors": object_headers(
        "Name",
        "Description",
        "Block Malicious URL",
        "Scan Botnet Connections",
        "Extended Log",
        "Replacement Message Group",
        "Entry Count",
        "VDOM",
    ),

    "IPS Sensor Entries": child_headers(
        "Sensor",
        "Entry ID",
        "Signature IDs",
        "CVEs",
        "Applications",
        "OS",
        "Protocols",
        "Severities",
        "Location",
        "Default Action",
        "Default Status",
        "Action",
        "Status",
        "Log",
        "Log Packet",
        "Log Attack Context",
        "Rate Count",
        "Rate Duration",
        "Rate Mode",
        "Rate Track",
        "Quarantine",
        "Quarantine Expiry",
        "Quarantine Log",
        "Vulnerability Types",
        "VDOM",
    ),

    "IPS Exempt IPs": child_headers(
        "Sensor",
        "Entry ID",
        "Exempt IP ID",
        "Source IP",
        "Destination IP",
        "VDOM",
    ),

    "Security Profiles": object_headers(
        "Name",
        "Antivirus",
        "IPS Sensor",
        "Web Filter",
        "File Filter",
        "SSL/SSH Profile",
        "VDOM",
    ),

    "External Resources": object_headers(
        "Name",
        "Resource",
        "Type",
        "Refresh Rate",
        "Comments",
        "VDOM",
    ),

    "FortiGate Source Configuration": (
        "Category",
        "Source Path",
        "Object",
        "Source ID",
        "Parent / Subsection",
        "Operation",
        "Setting",
        "Value",
        "Analysis Status",
        "Manual Review",
    ),

    "Firewall Policy Source Settings": (
        "Source Policy ID",
        "Policy Name",
        "Operation",
        "Setting",
        "Ordered Source Values",
    ),

    "Interface Source Settings": (
        "Interface",
        "Setting",
        "Value",
        "Extraction Status",
    ),

    "Interface Nested Configuration": (
        "Interface",
        "Config Path",
        "Node Type",
        "Object / Edit",
        "Operation",
        "Setting",
        "Value",
        "Extraction Status",
        "Manual Review",
    ),

    "Unresolved References": (
        "Source VDOM",
        "Source Type",
        "Source Object",
        "Field",
        "Reference",
        "Expected Type",
        "Result",
        "Reason",
    ),

    "Warnings": (
        "ID",
        "Category",
        "Message",
    ),

    "Unsupported": (
        "Section",
        "Item",
        "Status",
        "Reason",
        "Manual Review",
        "Raw Capture",
    ),

    "Source Inventory": (
        "Domain",
        "Scope Type",
        "Scope Name",
        "Source Path",
        "Object Name",
        "Setting",
        "Value",
        "Extraction Status",
        "Manual Review",
    ),

    "Extraction Coverage": (
        "Source Section",
        "Found",
        "Source Objects",
        "Parsed Objects",
        "Status",
        "Semantic Level",
        "Parser Handler",
        "Line Start",
        "Line End",
        "Semantic Unknowns",
        "Notes",
    ),
}


SOURCE_ONLY_SHEETS = (
    "System Settings",
    "DNS Settings",
    "NTP Settings",
    "Schedules",
    "Schedule Groups",
    "Local-In Policies",
    "Multicast Policies",
    "Policy Routes",
    "Routing Protocol Settings",
    "Session TTL Settings",
    "Session TTL Overrides",
    "SD-WAN SLAs",
    "SD-WAN Duplication",
    "SD-WAN Neighbors",
    "SD-WAN Rule SLAs",
    "SSL VPN Portal Split DNS",
    "SSL VPN Portal MAC Rules",
    "SSL VPN Portal OS Checks",
    "SSL VPN Bookmark Groups",
    "SSL VPN Bookmarks",
    "SSL VPN Bookmark Form Data",
    "SSL VPN Landing Pages",
    "SSL VPN Landing Form Data",
    "LDAP Servers",
    "RADIUS Servers",
    "RADIUS Accounting Servers",
    "TACACS+ Servers",
    "SAML Servers",
    "FSSO Servers",
    "FSSO AD Groups",
    "FSSO Polling",
    "FortiTokens",
    "Authentication Schemes",
    "Authentication Rules",
    "Authentication Sequences",
    "Identity Server Endpoints",
    "Source Security Profile Setting",
    "SSL TLS Service Profiles",
    "Internet Service Definitions",
    "Internet Service Def Entries",
    "Internet Service Def Ports",
    "Custom Internet Services",
    "Custom IS Entries",
    "Custom IS Ports",
    "Custom Internet Service Groups",
    "Internet Service Groups",
    "IS Additions",
    "IS Addition Entries",
    "IS Addition Ports",
    "IS Appends",
    "IS Extensions",
    "IS Extension Disabled",
    "IS Extension Entries",
    "IS Extension Ports",
    "DoS Policies",
    "DoS Anomalies",
    "Firewall Sniffer",
    "IPv6 EH Filter",
)

for sheet_name in SOURCE_ONLY_SHEETS:
    SHEET_HEADERS[sheet_name] = SOURCE_HEADERS

del sheet_name